### ISSUE TITLE
Provide annotated example yaml config file

### ISSUE THREAD

**Issue by StevenACoffman** [chanzuckerberg/blessclient#68]
I looked at the config.go, and lifted all the structs and some code to dump out this default config:
```
version: 0
client_config:
  configfile: /Users/scoffman/.blessclient/config.yml
  aws_user_profile: ""
  ssh_private_key: /Users/scoffman/.ssh/id_ed25519
  update_ssh_agent: false
  duration: 30m0s
  remote_users: []
  bastion_ips: []
lambda_config:
  role_arn: ""
  function_name: ""
```
It might be nice for other people if a complete, commented yaml file was available for documentation purposes.
