### ISSUE TITLE
Support EC2 metadata service credentials

### ISSUE THREAD

**Issue by StevenACoffman** [chanzuckerberg/blessclient#70]
We use [aws-vault](https://github.com/99designs/aws-vault) which keeps actual credentials in your keychain, and supports a mock ec2 metadata service to provide them to AWS SDK calls. I would like to use blessclient but currently I am getting the following error:

```
ERRO[0005] Error in region us-east-1: Error requesting kmsauth token: KMS encryption failed: NoCredentialProviders: no valid providers in chain. Deprecated.
```
I am using this config (account numbers redacted):
```
client_config:
  configfile: /Users/scoffman/.blessclient/config.yml
  aws_user_profile: ithakasequoia
  aws_username: scoffman
  ssh_private_key: /Users/scoffman/.ssh/bless_rsa_private_key
  update_ssh_agent: false
  duration: 12h0m0s
  remote_users:
  - ec2-user
  bastion_ips:
  - 141.211.141.211
lambda_config:
  role_arn: arn:aws:iam::XXXXXXX:role/sequoia-DevelopmentV1
  function_name: arn:aws:lambda:us-east-1:XXXXXX:function:bless_kms_lambda
  regions:
  - aws_region: us-east-1
    kms_auth_key_id: XXXXX-02ad-XXXX-8507-2ceebd2a4ae0
```
